### ISSUE TITLE
Add tracking additional metadata in the `pageView`

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/chrome-extension#17]
In order to track richer pageView data when someone is browsing we want to pass the following additional fields in `event_data` to improve classification for machine learning models:

- [ ] Log `page_title`
- [ ] Log meta `description` as a list
- [ ] Log meta `keywords` as a list
